// Copyright 2026 Marcelo Cantos
// SPDX-License-Identifier: Apache-2.0

// Package doit absorbs the real marcelocantos/doit Engine into jevons
// (🎯T8.3): Evaluate / Execute, L1/L2/L3 policy chain, capability registry,
// and hash-chained audit log. Config and audit live under a state directory
// so the daemon does not share the owner's global ~/.doit store in tests.
package doit

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	doitengine "github.com/marcelocantos/doit/engine"
)

// Re-export the public engine request/result types so callers do not need
// a second import of github.com/marcelocantos/doit/engine for the common path.
type (
	Request    = doitengine.Request
	Result     = doitengine.Result
	EvalResult = doitengine.EvalResult
	Engine     = doitengine.Engine
)

// OpenArgs configures a hermetic (or production) engine under StateDir.
type OpenArgs struct {
	// StateDir holds config.yaml, audit.jsonl, and L2 policy store.
	// Required.
	StateDir string
	// Level3Enabled turns on the LLM gatekeeper. Tests leave this false.
	Level3Enabled bool
	// Dangerous enables the dangerous capability tier (default false).
	Dangerous bool
}

// Open creates a doit Engine with isolated config under StateDir.
// L1 and L2 are always on; L3 defaults off for hermetic safety.
func Open(args OpenArgs) (*Engine, error) {
	if strings.TrimSpace(args.StateDir) == "" {
		return nil, fmt.Errorf("doit: StateDir required")
	}
	if err := os.MkdirAll(args.StateDir, 0o700); err != nil {
		return nil, fmt.Errorf("doit: mkdir: %w", err)
	}
	cfgPath := filepath.Join(args.StateDir, "config.yaml")
	auditPath := filepath.Join(args.StateDir, "audit.jsonl")
	l2Path := filepath.Join(args.StateDir, "learned-policy.json")
	// Always (re)write a tighten-only hermetic config so tests and daemons
	// do not inherit the operator's global L2 store or audit path.
	yaml := fmt.Sprintf(`# Generated by jevons internal/doit — do not hand-edit for production
# overlays; use a project .doit/config.yaml instead.
tiers:
  read: true
  build: true
  write: true
  dangerous: %t
policy:
  level1_enabled: true
  level2_enabled: true
  level2_path: %q
  level3_enabled: %t
audit:
  path: %q
  max_size_mb: 50
`, args.Dangerous, l2Path, args.Level3Enabled, auditPath)
	if err := os.WriteFile(cfgPath, []byte(yaml), 0o600); err != nil {
		return nil, fmt.Errorf("doit: write config: %w", err)
	}
	eng, err := doitengine.New(doitengine.Options{ConfigPath: cfgPath})
	if err != nil {
		return nil, fmt.Errorf("doit: new engine: %w", err)
	}
	return eng, nil
}

// PolicyMeta is the slice of an Evaluate/Execute result surfaced on jwork
// results and worker rows (🎯T8.3 acceptance: policy decisions in metadata).
type PolicyMeta struct {
	Decision string `json:"decision"`
	Level    int    `json:"level"`
	Reason   string `json:"reason,omitempty"`
	RuleID   string `json:"rule_id,omitempty"`
	AuditSeq uint64 `json:"audit_seq,omitempty"`
}

// MetaFromEval maps an EvalResult to PolicyMeta.
func MetaFromEval(r *EvalResult) PolicyMeta {
	if r == nil {
		return PolicyMeta{}
	}
	return PolicyMeta{
		Decision: r.Decision,
		Level:    r.Level,
		Reason:   r.Reason,
		RuleID:   r.RuleID,
	}
}

// MetaFromResult maps an Execute Result to PolicyMeta.
func MetaFromResult(r *Result) PolicyMeta {
	if r == nil {
		return PolicyMeta{}
	}
	return PolicyMeta{
		Decision: r.PolicyDecision,
		Level:    r.PolicyLevel,
		Reason:   r.PolicyReason,
		RuleID:   r.PolicyRuleID,
		AuditSeq: r.AuditSeq,
	}
}

// GateSpawn evaluates whether a jwork dispatch is permitted under policy.
// The synthetic command "jwork" is not a capability — we gate via a safe
// no-op Execute of `true` after Evaluate of the justification, and always
// run Evaluate on a representative shell that encodes denial of catastrophe.
//
// Practical rule: if the task text itself embeds an L1-denied pattern as a
// shell fragment (e.g. "rm -rf /"), deny at L1. Otherwise Evaluate `true`
// with the task as justification so the audit log records the dispatch, and
// allow when the decision is not "deny".
func GateSpawn(ctx context.Context, eng *Engine, task, cwd string) PolicyMeta {
	if eng == nil {
		return PolicyMeta{Decision: "allow", Level: 0, Reason: "doit engine not configured"}
	}
	// Scan task for classic L1-denied catastrophic shells so jwork cannot
	// be used as a policy bypass for "please run: rm -rf /".
	if cat := catastrophicShell(task); cat != "" {
		ev := eng.Evaluate(ctx, Request{
			Command:       cat,
			Justification: "jwork task embeds shell",
			SafetyArg:     "preflight deny check",
			Cwd:           cwd,
		})
		m := MetaFromEval(ev)
		if m.Decision == "" {
			m.Decision = "deny"
			m.Reason = "catastrophic shell in task"
			m.Level = 1
		}
		return m
	}
	// Record the dispatch itself via Evaluate of a safe builtin; when L3
	// is off, bare commands often escalate — we treat non-deny as allow for
	// spawn (workers keep provider --always-approve; doit gates release-class
	// actions, not every jwork).
	ev := eng.Evaluate(ctx, Request{
		Command:       "true",
		Justification: "jwork dispatch: " + truncate(task, 200),
		SafetyArg:     "ephemeral worker spawn under jevons",
		Cwd:           cwd,
	})
	m := MetaFromEval(ev)
	if m.Decision == "deny" {
		return m
	}
	// Execute a no-op so the hash-chained audit log gets a real entry for
	// the worker spawn path (AuditSeq on metadata).
	res := eng.Execute(ctx, Request{
		Command:       "true",
		Justification: "jwork spawn audit",
		SafetyArg:     "record spawn in audit chain",
		Cwd:           cwd,
	})
	pm := MetaFromResult(res)
	if pm.Decision == "" || pm.Decision == "escalate" {
		// Spawn remains free when policy only escalates; merges/releases
		// still hit real denials. Record level/reason from Evaluate.
		pm.Decision = "allow"
		if m.Level > 0 {
			pm.Level = m.Level
		}
		if pm.Reason == "" {
			pm.Reason = m.Reason
			if pm.Reason == "" {
				pm.Reason = "jwork spawn allowed (non-deny policy)"
			}
		}
		if pm.RuleID == "" {
			pm.RuleID = m.RuleID
		}
	}
	return pm
}

func catastrophicShell(task string) string {
	lower := strings.ToLower(task)
	// Subset of L1 permanent blocks that must never ride through jwork text.
	patterns := []string{
		"rm -rf /",
		"rm -rf /*",
		"rm -fr /",
		"chmod -r 000 /",
		"chmod 000 /",
	}
	for _, p := range patterns {
		if strings.Contains(lower, p) {
			return p
		}
	}
	return ""
}

func truncate(s string, n int) string {
	if n <= 0 || len(s) <= n {
		return s
	}
	return s[:n] + "…"
}
