// Copyright 2026 Marcelo Cantos
// SPDX-License-Identifier: Apache-2.0

/** Locked census of pre-React UI targets (🎯T540.1). Cutoff = first React commit 2026-08-22. */

export const CENSUS_CUTOFF = '2026-08-22';

export type CensusKind = 'visible' | 'exception';
export type CensusSurface =
  | 'transcript'
  | 'fold'
  | 'composer'
  | 'fleet'
  | 'aside'
  | 'frontier'
  | 'ticker'
  | 'chrome'
  | 'other'
  | 'impl'
  | 'doctrine'
  | 'delivery'
  | 'platform';

export type CensusRow = {
  id: string;
  kind: CensusKind;
  surface: CensusSurface;
  name: string;
  journeys?: readonly string[];
  families?: readonly string[];
  reason?: string;
};

export const CENSUS: readonly CensusRow[] = [
  { id: "T13", kind: "exception", surface: "platform", name: "Full-duplex voice interaction", reason: "voice gated on T37 — not React cockpit chrome" },
  { id: "T21", kind: "visible", surface: "composer", name: "Wispr Flow dictation into the Jevons UI produces full sentences", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T23", kind: "visible", surface: "transcript", name: "Chat panel visually differentiates user / assistant / worker (system) messages", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T27.6", kind: "exception", surface: "other", name: "The server-side server-driven-UI producer is rebuilt with multi-provider composition", reason: "server-driven ViewNode producer — not the React cockpit" },
  { id: "T27.7", kind: "exception", surface: "other", name: "Jevons owns a desktop menu-bar/tray head rendering the aggregated hub UI", reason: "desktop tray head — not cockpit/chat/composer/tree" },
  { id: "T30.2", kind: "visible", surface: "transcript", name: "Long in-flight assistant replies keep follow-scroll pinned to the true bottom until the turn seals", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T39", kind: "visible", surface: "chrome", name: "Chat UI paints idle in #status after every overseer turn — never leftover Jevons is working", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T52", kind: "visible", surface: "transcript", name: "Rewind works on the Grok ACP overseer", journeys: ["send", "connect"], families: ["fold", "transcript-geom"] },
  { id: "T53", kind: "exception", surface: "other", name: "The released jevonsd binary serves the web UI standalone — no repo checkout required", reason: "release embed of web UI — serve path, not React paint" },
  { id: "T55", kind: "visible", surface: "fold", name: "Oversized chat content auto-collapses to a bounded height with expand-on-demand, so load doesn't thrash", journeys: ["fold-md"], families: ["clip", "markdown", "fold"] },
  { id: "T56", kind: "exception", surface: "impl", name: "The chat history view is virtualised — only on-screen messages are in the DOM", reason: "vanilla virtual-list node-count — React owns reconciliation" },
  { id: "T57", kind: "visible", surface: "fold", name: "Oversized turns cost bounded browser work: preview-only render up front, full content parsed lazily on expand, no per-chunk re-parse", journeys: ["fold-md"], families: ["clip", "markdown", "fold"] },
  { id: "T58", kind: "visible", surface: "transcript", name: "Daemon restart resumes the overseer's real session — no recap/rotation, invisible in chat and journal", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T59", kind: "visible", surface: "fold", name: "The chat renderer draws mermaid diagrams from fenced ```mermaid blocks instead of showing raw source", journeys: ["fold-md"], families: ["clip", "markdown", "fold"] },
  { id: "T61", kind: "exception", surface: "delivery", name: "Worker replies reach the overseer — a directed worker's completion is delivered, not silently dropped", reason: "overseer delivery / queue MCP path, not cockpit paint" },
  { id: "T62", kind: "exception", surface: "delivery", name: "Async overseer notifications survive an overseer-busy collision — queued and delivered, never dropped on 'prompt already in flight'", reason: "overseer delivery / queue MCP path, not cockpit paint" },
  { id: "T63", kind: "visible", surface: "transcript", name: "Only genuine user turns render as chat bubbles; agent/system notifications fold into an informative activity strip", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T64", kind: "visible", surface: "transcript", name: "Activity-strip tool steps show a short argument summary, not just the tool name", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T65", kind: "visible", surface: "aside", name: "Owner has attention threads in the human↔overseer chat — capture without commit, park/pursue, visible stack to switch focus", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T66", kind: "visible", surface: "fold", name: "Latest assistant response starts expanded (same rule as latest user request)", journeys: ["fold-md"], families: ["clip", "markdown", "fold"] },
  { id: "T68", kind: "visible", surface: "fleet", name: "Right-side worker panel shows who-started-whom as a relationship tree", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T69", kind: "visible", surface: "composer", name: "Chat composer height avoids constant scrollbar flicker while typing", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T70", kind: "visible", surface: "composer", name: "Chat composer layout keeps the latest assistant reply readable while the owner types", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T70.1", kind: "visible", surface: "composer", name: "Composer growth does not cover the latest assistant response", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T71", kind: "visible", surface: "chrome", name: "In-flight #status paints the ACP phase word (received/thinking/tool/writing/…), not Jevons is working", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T72", kind: "visible", surface: "fleet", name: "RHS fleet panel reflects the full live agent graph", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T72.1", kind: "visible", surface: "fleet", name: "Every live fleet agent appears in the RHS panel while it exists", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T73", kind: "visible", surface: "fleet", name: "Agent click no longer opens the obsolete black TMUX/detail panel", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T74", kind: "visible", surface: "fold", name: "Fenced code blocks get automatic syntax highlighting for a large set of common languages", journeys: ["fold-md"], families: ["clip", "markdown", "fold"] },
  { id: "T75", kind: "visible", surface: "fold", name: "Owner request bubbles render quote notation correctly", journeys: ["fold-md"], families: ["clip", "markdown", "fold"] },
  { id: "T76", kind: "visible", surface: "composer", name: "Owner can paste images into the chat composer and they reach the agent turn", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T77", kind: "visible", surface: "fold", name: "Oversized non-latest messages collapse for both user and assistant roles", journeys: ["fold-md"], families: ["clip", "markdown", "fold"] },
  { id: "T80", kind: "visible", surface: "composer", name: "Composer lightly tidies bulk Wispr/dictation inserts (trim, capitalize, terminal punctuation)", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T81", kind: "visible", surface: "fleet", name: "Large multi-agent work is watchable live in a first-class UI (RHS panel baseline; optional bullseye intent-graph resolution)", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T82", kind: "visible", surface: "fleet", name: "Overseer UI and fleet state refresh via file-watcher / event push, not polling", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T83", kind: "visible", surface: "chrome", name: "Overseer UI has a persistent visualization surface for project/agent graphs (bullseye, Mermaid, later JSON viz)", journeys: ["ticker"], families: ["frontier", "aside-sidebar"] },
  { id: "T83.1", kind: "visible", surface: "chrome", name: "Owner can open a bullseye/Mermaid graph in a dedicated tab and copy Mermaid source and image (multi-MIME when supported)", journeys: ["ticker"], families: ["frontier", "aside-sidebar"] },
  { id: "T84", kind: "visible", surface: "fleet", name: "RHS agent path display uses a GitHub icon instead of bare ~ for compacted workdirs", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T87", kind: "visible", surface: "transcript", name: "Jevons embodies owner impatience — snappy feedback, zero silent waits, bias to act", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T88", kind: "visible", surface: "composer", name: "Owner chat history navigation (up/down) matches shell/Grok expectations and redo intent", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T89", kind: "visible", surface: "transcript", name: "Long-running and multi-agent work reports live progress to the owner without babysitting", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T91", kind: "visible", surface: "transcript", name: "Each transcript item shows an accurate timestamp on hover (tooltip)", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T93", kind: "visible", surface: "aside", name: "Owner can file a bullseye target out-of-band without a full attention thread", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T94", kind: "visible", surface: "transcript", name: "Owner chat self-heals from stuck or empty overseer turns without manual session mint", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T95", kind: "visible", surface: "aside", name: "Filing a bullseye target is a short-lived aside: target: prefix, clarify, file, auto-close", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T95.1", kind: "visible", surface: "aside", name: "Completed asides leave screen chrome — discoverable archive, not parked chips or main-flow pollution", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T96", kind: "exception", surface: "doctrine", name: "Grok CLI capability audit maps which features Jevons should embody conversationally (voice-first, not slash-command parity)", reason: "Grok CLI capability research note" },
  { id: "T99", kind: "visible", surface: "aside", name: "Continuation statements route into the matching thread without full re-discussion in main", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T103", kind: "visible", surface: "other", name: "Sooner tranche: live progress, fleet tree+sort, basic impatience/alter-ego, and RSI target-filing — parallelizable with week-of-use batch under clear lanes", journeys: ["ticker"] },
  { id: "T105.2", kind: "exception", surface: "doctrine", name: "T65 prefix-first attention threads have hermetic UI oracle coverage", reason: "how we test T65 prefix UX — not a pixel" },
  { id: "T105.4", kind: "exception", surface: "doctrine", name: "T66/T77 collapse UX stays gated by collapse-test hermetic (no redundant journey)", reason: "collapse-test.js gate — how we test T66/T77" },
  { id: "T106", kind: "visible", surface: "fold", name: "Collapsed tall bubbles are a border-flush pocket (dark scrim + edge tab); short messages have no tab", journeys: ["fold-md"], families: ["clip", "markdown", "fold"] },
  { id: "T109", kind: "exception", surface: "other", name: "Unattended safe batch of frontier leaves can be completed by agents without owner decision or validation gates", reason: "unattended batch consume — automation, not frontier table" },
  { id: "T110", kind: "exception", surface: "other", name: "Self-test orchestrator runs classed packs on sites live | drill | ci with one report schema", reason: "self-test orchestrator / pack schema" },
  { id: "T110.1", kind: "exception", surface: "impl", name: "Web client layout probe surface exposes composer/messages/last-reply metrics", reason: "window.JevonsProbe.snapshot test hook, not owner chrome" },
  { id: "T110.3", kind: "exception", surface: "other", name: "First packs health-L1, composer-growth-L2, and agents-parent-L1 are registered and gradable", reason: "self-test pack registration — not cockpit paint" },
  { id: "T110.4", kind: "exception", surface: "other", name: "Drill site is documented with a minimal ensure-isolate path (full drill tab may be stub)", reason: "drill-site docs — not cockpit paint" },
  { id: "T111.3", kind: "visible", surface: "fleet", name: "All fleet spawn paths record parent lineage so the RHS tree matches who-started-whom", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T113", kind: "visible", surface: "composer", name: "Owner chat queues follow-up sends instead of Enter interrupting the in-flight turn — Grok-parity queue UI and keys", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T114", kind: "exception", surface: "doctrine", name: "Fleet model is unified: an aside is a kind of agent — one registry, one talk path, purpose distinguishes side chat", reason: "fleet/aside unification instructional doctrine" },
  { id: "T115", kind: "visible", surface: "fleet", name: "RHS root overseer omits ~/.jevons/jevons path; asides use 💡 description chrome without path bleed", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T116", kind: "visible", surface: "transcript", name: "Activity-strip tool steps show human-useful argument values, not schema key dumps", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T117", kind: "visible", surface: "ticker", name: "Cost ticker is trustworthy — real non-zero rates when spend is happening, or the UI is removed", journeys: ["ticker"], families: ["plan-ticker"] },
  { id: "T118", kind: "visible", surface: "fleet", name: "RHS fleet rows surface brief automated status/progress instead of redundant worker paths", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T119", kind: "visible", surface: "transcript", name: "Transcript is fully loaded in-browser, windowed for render stress, recent-first, whole-chunk only", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T119.1", kind: "visible", surface: "transcript", name: "Reload and reconnect history replay does not scroll-parade to the live end", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T119.2", kind: "exception", surface: "impl", name: "Transcript view height backfill is windowed around the viewport, not the whole history", reason: "height-backfill / offsetTop geometry internals" },
  { id: "T119.3", kind: "exception", surface: "impl", name: "Transcript is an absolute-position virtual list: O(viewport) nodes, mid-list collapse does not require sibling shells", reason: "vanilla virtualizeMessages reconciler" },
  { id: "T119.4", kind: "exception", surface: "impl", name: "Transcript list is a specialized reconciler: model is left, DOM is right, IR is attach+geometry not an element tree", reason: "vanilla model/DOM/IR attach reconciler" },
  { id: "T119.5", kind: "exception", surface: "impl", name: "Transcript display fold is incremental and equal to a full f(events) replay", reason: "incremental fold ≡ displayFromEvents IR spec" },
  { id: "T119.6", kind: "visible", surface: "transcript", name: "Live tool-step capsules do not stack or overlap — one open slot is one marker", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T119.7", kind: "visible", surface: "transcript", name: "Live-streamed bubbles do not overlap — prefix updates when a row grows", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T119.8", kind: "visible", surface: "transcript", name: "Steps capsule is painted from fold rows — the host keeps no open-slot state", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T122", kind: "visible", surface: "transcript", name: "Activity-strip tool step tooltips do not needlessly wrap — readable single-line (or wide) chrome", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T123", kind: "visible", surface: "composer", name: "Composer message entry default height matches the send button — compact, not oversized", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T124", kind: "visible", surface: "fleet", name: "RHS fleet selection shows that agent’s full transcript (asides and workers), out of band from main chat", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T126", kind: "visible", surface: "composer", name: "Home and End move the caret to start and end of the composer message box", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T127", kind: "visible", surface: "composer", name: "Dedicated hotkey always focuses the main chat message box", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T128.2", kind: "exception", surface: "impl", name: "Soft-empty transcript and related 200-empty API paths leave empty_reason fingerprints", reason: "empty_reason API fingerprints — server, not paint" },
  { id: "T131", kind: "visible", surface: "frontier", name: "RHS bottom pane can show a live bullseye frontier table (tabbed with agent transcript inspect)", journeys: ["frontier"], families: ["frontier"] },
  { id: "T132", kind: "visible", surface: "composer", name: "Composer send/interject shortcuts: Ctrl+Enter immediate send; Alt+Enter empty pops last message as interjection", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T133", kind: "visible", surface: "composer", name: "Empty-composer Wispr seed stays effective but is invisible until real draft text arrives", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T134", kind: "visible", surface: "aside", name: "Attention / thread chrome is legible and non-accumulating — not a wall of open/parked chips", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T135", kind: "visible", surface: "aside", name: "Auto-matched messages stay on main by default; owner can opt-in switch to the suggested thread", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T136", kind: "visible", surface: "aside", name: "Asides live only in the RHS fleet tree — no top attention chip bar", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T138", kind: "visible", surface: "transcript", name: "Typed degraded chat mode when overseer is down — banner, no thrash", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T140", kind: "visible", surface: "other", name: "Reconnect and degraded-mode health are first-class in logs and UI chrome", journeys: ["ticker"] },
  { id: "T141", kind: "exception", surface: "impl", name: "Main UI boot state is TDZ-safe and failure-isolated", reason: "vanilla boot order let/const TDZ — applyTheme/connect" },
  { id: "T142", kind: "exception", surface: "impl", name: "Chatlog replay is cheap — sealed turns not token-stream firehose", reason: "wire replay internals — sealed vs token-stream firehose" },
  { id: "T143", kind: "visible", surface: "transcript", name: "Soft reconnect preserves transcript DOM — no wipe/replay thrash", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T145", kind: "visible", surface: "fold", name: "Assistant messages that open with a fenced code block always render as a code block — never fused to a preceding blurb", journeys: ["fold-md"], families: ["clip", "markdown", "fold"] },
  { id: "T146", kind: "visible", surface: "fold", name: "Prose that mentions fence markers does not accidentally open code blocks", journeys: ["fold-md"], families: ["clip", "markdown", "fold"] },
  { id: "T147", kind: "visible", surface: "fold", name: "Stream coalesce at ACP/assistant segment boundaries inserts newline before fence openers", journeys: ["fold-md"], families: ["clip", "markdown", "fold"] },
  { id: "T149", kind: "visible", surface: "composer", name: "Home and End again move the caret to start and end of the composer message box", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T150", kind: "visible", surface: "fold", name: "Streaming assistant markdown renders complete emphasis and structure — not raw asterisks until reload", journeys: ["fold-md"], families: ["clip", "markdown", "fold"] },
  { id: "T151", kind: "visible", surface: "transcript", name: "Chat and UI links always open in a new browser tab", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T152", kind: "visible", surface: "aside", name: "Target-filing aside dismisses fleet RHS chrome when __TARGET_FILED__ is confirmed", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T153", kind: "visible", surface: "composer", name: "Keyboard Tab rarely leaves the composer — collapse tabs and similar chrome are pointer-only", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T154", kind: "visible", surface: "composer", name: "Composer send queue survives reload and reconnect", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T155", kind: "exception", surface: "other", name: "New unattended frontier leaves get a worker immediately without waiting for owner", reason: "unattended frontier spawn policy — daemon, not table paint" },
  { id: "T157", kind: "visible", surface: "aside", name: "RHS agent transcript inspect renders assistant bodies as full markdown", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T159", kind: "visible", surface: "transcript", name: "One assistant bubble per terminal stop_reason — tool rounds never seal mid-reply", journeys: ["send", "connect"], families: ["fold", "transcript-geom"] },
  { id: "T161", kind: "visible", surface: "transcript", name: "Assistant stream joins preserve paragraph breaks between segments", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T164", kind: "visible", surface: "aside", name: "Filed target-asides leave no owner-visible chrome or fleet 💡 row", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T166", kind: "visible", surface: "fold", name: "Expanded tall bubbles clear last text line above collapse tab", journeys: ["fold-md"], families: ["clip", "markdown", "fold"] },
  { id: "T167", kind: "visible", surface: "aside", name: "RHS agent Transcript is a single scroll surface — no nested per-turn scroll regions", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T168", kind: "visible", surface: "frontier", name: "Frontier tab loads frontier data without HTTP 404", journeys: ["frontier"], families: ["frontier"] },
  { id: "T173", kind: "visible", surface: "frontier", name: "Frontier table is headerless with abbreviated status and fanout as N᚛ plus hover detail", journeys: ["frontier"], families: ["frontier"] },
  { id: "T174", kind: "visible", surface: "frontier", name: "Frontier table width is constrained to the RHS container — no horizontal overflow of the pane", journeys: ["frontier"], families: ["frontier"] },
  { id: "T175", kind: "visible", surface: "frontier", name: "Owner-facing hover explanations appear instantly — no delayed native title tooltips", journeys: ["frontier"], families: ["frontier"] },
  { id: "T176", kind: "exception", surface: "doctrine", name: "Overseer status language is in progress vs live — live means product-visible only", reason: "persona/AGENTS in-progress vs live vocabulary — no pixel" },
  { id: "T177", kind: "visible", surface: "frontier", name: "Frontier table columns do not overlap — three chrome columns have real fixed widths, name takes the rest", journeys: ["frontier"], families: ["frontier"] },
  { id: "T179", kind: "visible", surface: "frontier", name: "Frontier status glyph is normal case (no small-caps) and id/fanout columns are tight", journeys: ["frontier"], families: ["frontier"] },
  { id: "T181", kind: "visible", surface: "frontier", name: "Frontier ID (and name) hover shows a rich markdown target card — not only the expanded name", journeys: ["frontier"], families: ["frontier"] },
  { id: "T182", kind: "visible", surface: "frontier", name: "Frontier status and fanout columns are tightly packed; each row has a play control that asks the PO to start that target", journeys: ["frontier"], families: ["frontier"] },
  { id: "T183", kind: "visible", surface: "composer", name: "Composer draft remains visible after page reload without requiring an edit keystroke", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T184", kind: "visible", surface: "frontier", name: "Frontier target hover is a full semantic card — common fields, markdown bodies, mermaid dependency minigraph", journeys: ["frontier"], families: ["frontier"] },
  { id: "T185", kind: "visible", surface: "frontier", name: "Frontier toolbar has a Graph control that opens a near-full-page unachieved dependency graph", journeys: ["frontier"], families: ["frontier"] },
  { id: "T186", kind: "visible", surface: "frontier", name: "Frontier hover cards stay open while the pointer is over the card so their content can be scrolled", journeys: ["frontier"], families: ["frontier"] },
  { id: "T187", kind: "visible", surface: "frontier", name: "InstantTip cards never auto-timeout — dismiss only when pointer leaves the card (or host without entering the card)", journeys: ["frontier"], families: ["frontier"] },
  { id: "T189", kind: "visible", surface: "frontier", name: "Escape key closes the Frontier Graph / mermaid viz panel when it is open", journeys: ["frontier"], families: ["frontier"] },
  { id: "T190", kind: "visible", surface: "frontier", name: "Unachieved Frontier Graph layout fits the large panel without insane horizontal sprawl", journeys: ["frontier"], families: ["frontier"] },
  { id: "T192", kind: "visible", surface: "composer", name: "Alt+Enter on seed-only composer behaves as empty control", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T196", kind: "visible", surface: "frontier", name: "Failed product fetches in chrome panels show actionable errors — not the empty generic paste shell", journeys: ["frontier"], families: ["frontier"] },
  { id: "T198", kind: "visible", surface: "frontier", name: "Frontier rows show Jevons work engagement — in-progress sinks bottom with Stop, not a bullseye status rewrite", journeys: ["frontier"], families: ["frontier"] },
  { id: "T199", kind: "visible", surface: "frontier", name: "Target IDs sort by numeric segments (natural/version order) everywhere frontier and graph order them", journeys: ["frontier"], families: ["frontier"] },
  { id: "T200", kind: "visible", surface: "fleet", name: "Domain portfolios group related products under the root fleet tree without a permanent GM agent", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T202", kind: "visible", surface: "chrome", name: "Mid-turn #status updates in place to the latest phase word — correspondent names do not accumulate", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T203", kind: "visible", surface: "frontier", name: "Only one Frontier InstantTip card is open at a time — opening another dismisses the rest", journeys: ["frontier"], families: ["frontier"] },
  { id: "T204", kind: "visible", surface: "other", name: "Cockpit converges to a usable owner chat and live fleet: overseer Alive+attached+turn-usable; stuck-busy auto-unstuck; dead workers recovered; idle mission workers nudged — not process-liveness alone", journeys: ["ticker"] },
  { id: "T205", kind: "visible", surface: "aside", name: "RHS agent inspect is the main transcript experience in microcosm — same body paint, stickiness, and update behaviour", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T208", kind: "visible", surface: "frontier", name: "RHS Frontier tab stays selected until the owner chooses Transcript again — background transcript refresh does not steal the tab", journeys: ["frontier"], families: ["frontier"] },
  { id: "T209", kind: "exception", surface: "impl", name: "Agent inspect transcript uses the same live wire pathway as main chat — not a separate HTTP poll channel", reason: "inspect uses same WS family as main — transport, not paint" },
  { id: "T210", kind: "visible", surface: "transcript", name: "After rewind + resubmit of a modified owner message, assistant bubbles render each token once — no doubled words/characters", journeys: ["send", "connect"], families: ["fold", "transcript-geom"] },
  { id: "T211", kind: "visible", surface: "fleet", name: "Fleet agent chrome distinguishes process-alive from turn-busy — bare running is not shown as active work", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T213", kind: "exception", surface: "other", name: "Fleet inspect/status/transcript discovery covers Claude (and non-Grok) session stores — not only ~/.grok/sessions", reason: "session discovery across providers — inspect API, not paint" },
  { id: "T216", kind: "visible", surface: "aside", name: "RHS agent inspect paints assistant turns as real markdown HTML — same sealed product as main chat, owner-visible bold/fences/tables", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T217", kind: "visible", surface: "aside", name: "RHS agent inspect assistant bodies render markdown HTML (strong/pre) — not raw ** or textContent dumps", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T219", kind: "exception", surface: "other", name: "A durable background sentinel agent (ralph-style loop) continuously observes cockpit and fleet health, repairs what it can, and otherwise files a bullseye target and directs jevons-po to execute — without owner babysitting", reason: "background sentinel agent — ops, not cockpit chrome" },
  { id: "T221", kind: "visible", surface: "aside", name: "RHS agent inspect paints markdown for fleet user injects and MD-shaped user turns — not raw ** stars", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T222", kind: "exception", surface: "other", name: "Filing and frontier play cannot create duplicate same-mission targets or double-engaged implementers", reason: "duplicate-mission filing policy — not frontier paint" },
  { id: "T223", kind: "visible", surface: "transcript", name: "Owner follow-up while overseer is streaming always enqueues — never interleaves a user turn mid-assistant bubble (T113 regression)", journeys: ["send", "connect"], families: ["fold", "transcript-geom"] },
  { id: "T224", kind: "visible", surface: "transcript", name: "Overseer chat paste images and full turn bodies survive hard-reload and cross-browser session attach via server persistence with thumbnail delivery", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T227", kind: "visible", surface: "composer", name: "Alt+Enter empty composer pops last owner message into the draft again — product path works on daily UI", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T228", kind: "visible", surface: "composer", name: "Owner composer submit never silently drops a non-empty message — send, enqueue, or visible error", journeys: ["send", "composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T230", kind: "visible", surface: "frontier", name: "Frontier target hover cards never auto-dismiss while the pointer is over the card — no idle timeout", journeys: ["frontier"], families: ["frontier"] },
  { id: "T231", kind: "visible", surface: "frontier", name: "Frontier target cards use a single continuous hit-group for open/dismiss — no grace-timeout walk-away after leaving the card", journeys: ["frontier"], families: ["frontier"] },
  { id: "T233", kind: "visible", surface: "transcript", name: "Harness system-reminders and similar injects render as compacted activity nuggets with hover detail — not full user-shaped bubbles", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T235", kind: "visible", surface: "composer", name: "Alt+Enter empty/seed-only composer reliably pops the last owner message into the draft on daily UI", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T236", kind: "exception", surface: "other", name: "After provider outage or failed turns, open-mission fleet is re-pressured without owner continue", reason: "fleet re-pressure after outage — daemon recovery" },
  { id: "T237", kind: "visible", surface: "other", name: "Provider/ACP failures are classified: local vs backend-down vs unknown — not bare Internal error", journeys: ["ticker"] },
  { id: "T238", kind: "visible", surface: "transcript", name: "Overseer [silent] replies never appear in owner chat UI or chatlog bubbles", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T239", kind: "visible", surface: "composer", name: "Owner-typed messages and drafts survive daemon restart and brief disconnects without silent loss", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T240", kind: "visible", surface: "transcript", name: "Silent overseer turns are suppressed as a whole stream — not only when a single wire fragment starts with [silent]", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T241", kind: "visible", surface: "composer", name: "Alt+Enter force-sends: current composer draft if non-empty, else head of send queue", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T242", kind: "visible", surface: "transcript", name: "Owner-visible assistant replies stay in the transcript after seal — do not flash then disappear", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T245", kind: "visible", surface: "transcript", name: "Silent-only overseer turns do not leak into or coalesce with the next visible owner bubble", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T246", kind: "visible", surface: "fold", name: "New chat messages (user or agent) stay expanded until scrolled out of view by newer messages", journeys: ["fold-md"], families: ["clip", "markdown", "fold"] },
  { id: "T247", kind: "visible", surface: "aside", name: "Explicit aside prefixes (target:, aside:, capture:) immediately open the aside — no create-affordance step", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T248", kind: "visible", surface: "chrome", name: "Owner can drag-resize RHS sidebar width and the sidebar top/bottom split", journeys: ["ticker"], families: ["frontier", "aside-sidebar"] },
  { id: "T249", kind: "visible", surface: "transcript", name: "Streaming assistant replies do not temporarily appear as multiple split bubbles before coalescing", journeys: ["send", "connect"], families: ["fold", "transcript-geom"] },
  { id: "T250", kind: "visible", surface: "aside", name: "Asides are not visible in the main transcript — all aside interaction is via the sidebar Transcript tab", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T251", kind: "visible", surface: "aside", name: "Sidebar transcript view has its own message composer and send UX", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T252", kind: "visible", surface: "aside", name: "Sidebar auto-activates next attention-needing aside when composer empty; holds focus once user has typed", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T254.1", kind: "exception", surface: "other", name: "Daemon enforces unattended frontier consumption — every Build leaf has a worker or explicit park reason", reason: "daemon enforces frontier consumption — not table paint" },
  { id: "T255", kind: "visible", surface: "frontier", name: "Frontier play kickoff targets the selected agent’s product owner — not hard-coded jevons-po", journeys: ["frontier"], families: ["frontier"] },
  { id: "T256", kind: "visible", surface: "transcript", name: "Chat image thumbnails use high-quality resampling — never nearest-neighbour", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T257", kind: "visible", surface: "transcript", name: "Chat image thumbs dual-encode PNG vs JPEG — JPEG only when substantially smaller", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T258", kind: "visible", surface: "transcript", name: "Click chat image opens in-page full-res viewer with multi-image carousel", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T259", kind: "visible", surface: "transcript", name: "History hydrate cannot burn a core on large chatlogs", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T260", kind: "visible", surface: "transcript", name: "Working indicator stays visible until the owner-visible turn actually completes", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T261", kind: "visible", surface: "fold", name: "Messages near the end of the transcript that are still in view are never collapsed", journeys: ["fold-md"], families: ["clip", "markdown", "fold"] },
  { id: "T262.1", kind: "exception", surface: "doctrine", name: "Written doctrine: readiness set, not next-ticket; frontier strictly stronger than queues", reason: "frontier = ready-set written doctrine" },
  { id: "T262.2", kind: "exception", surface: "doctrine", name: "Multi-agent model evaluated: worker-per-frontier-leaf vs engagement policy", reason: "worker-per-leaf vs engagement policy design packet" },
  { id: "T263", kind: "visible", surface: "aside", name: "Owner freeform asides deliver the opening message and show working activity until first reply", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T264", kind: "visible", surface: "transcript", name: "Main transcript never paints raw [attention:…] / [target-aside:…] wire markers as owner bubbles", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T265", kind: "visible", surface: "aside", name: "Aside/agent Transcript pane is a microcosm of main chat — same look and behaviour, no recursive sidebar", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T266", kind: "visible", surface: "frontier", name: "Owner-facing target asks show built-in context chrome (repo / PO / product)", journeys: ["frontier"], families: ["frontier"] },
  { id: "T267", kind: "visible", surface: "frontier", name: "Target asks auto-select owning PO and highlight the target on Frontier", journeys: ["frontier"], families: ["frontier"] },
  { id: "T268", kind: "visible", surface: "frontier", name: "Frontier graphs scale up to fill the pane — single-graph case first", journeys: ["frontier"], families: ["frontier"] },
  { id: "T269", kind: "visible", surface: "aside", name: "Fleet tree asides show a hover-only dismiss (×) control on the right", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T270", kind: "visible", surface: "aside", name: "Owner can browse historical closed asides, with explicit asides delineated from target-asides", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T271", kind: "visible", surface: "frontier", name: "Frontier InstantTip cards dismiss when the pointer leaves the hit region (up/down from the trigger row)", journeys: ["frontier"], families: ["frontier"] },
  { id: "T272", kind: "visible", surface: "transcript", name: "Working indicator is level-triggered from live in-flight state — not edge-triggered kickoff", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T273", kind: "visible", surface: "transcript", name: "Speaker omit for overseer only; keep context chrome even when jevons-po", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T274", kind: "visible", surface: "frontier", name: "Orthograph (and large) target graph renders; no empty viewer + stuck Loading earlier loop", journeys: ["frontier"], families: ["frontier"] },
  { id: "T275", kind: "visible", surface: "aside", name: "RHS agent Transcript send delivers to the selected fleet agent", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T278", kind: "visible", surface: "frontier", name: "Frontier play kickoff shows spinning submitted chrome immediately", journeys: ["frontier"], families: ["frontier"] },
  { id: "T279", kind: "visible", surface: "transcript", name: "Owner-submitted chat messages stay visible after send (no silent disappear)", journeys: ["send", "connect"], families: ["fold", "transcript-geom"] },
  { id: "T280", kind: "visible", surface: "frontier", name: "Frontier Graph is owner-readable in one glance after hard-reload (visual smoke required)", journeys: ["frontier"], families: ["frontier"] },
  { id: "T281", kind: "visible", surface: "transcript", name: "Owner send paints exactly once in main chat and RHS transcript (no double bubble)", journeys: ["send", "connect"], families: ["fold", "transcript-geom"] },
  { id: "T285.1", kind: "exception", surface: "delivery", name: "A provider switch never starts work in the session that read the predecessor transcript", reason: "provider-switch handover seed shape — MCP, not tree paint" },
  { id: "T285.2", kind: "visible", surface: "fleet", name: "Fleet-tree icon menu migrates any agent; ! mark when its provider is ahead or hot", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T287", kind: "visible", surface: "fleet", name: "Fleet agent names show company icon + condensed model prefix", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T289", kind: "visible", surface: "transcript", name: "Owner UI remains smooth under normal fleet chat use (no constant stutter/jank)", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T292", kind: "exception", surface: "impl", name: "Every script index.html loads is embedded, so a released jevonsd serves the full UI standalone", reason: "embed.go must list every index.html script — serving hygiene" },
  { id: "T293", kind: "visible", surface: "fleet", name: "Grok model prefix uses Grok logo and always shows condensed version subscript", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T294", kind: "visible", surface: "frontier", name: "Frontier Graph fills the large pane with human-legible nodes after hard-reload", journeys: ["frontier"], families: ["frontier"] },
  { id: "T295", kind: "visible", surface: "fleet", name: "Claude model prefix uses Claude splat icon and drops leading zeros in version", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T296", kind: "visible", surface: "fleet", name: "Grok badge uses ring-slash logo and icon+version as one compact unit", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T298", kind: "visible", surface: "fleet", name: "Fleet model subscript is unambiguous — no letter reads as a digit", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T299", kind: "visible", surface: "fleet", name: "Model badges use authentic brand SVGs, integer version segments, and true sub-baseline (no O/0 ambiguity)", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T300", kind: "visible", surface: "transcript", name: "“Loading earlier…” never flashes unless the owner truly loads earlier history", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T301", kind: "visible", surface: "fleet", name: "Agent migrate preserves purpose (PO stays work, not flipped to aside)", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T302", kind: "visible", surface: "fleet", name: "Claude badge restores bold purple Opus O and shows real version when known", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T304", kind: "exception", surface: "other", name: "jevons_transcript_read returns the named agent's transcript, not the caller's", reason: "jevons_transcript_read caller vs named agent — MCP" },
  { id: "T306", kind: "visible", surface: "transcript", name: "Target-context chrome (repo · PO tab) appears only on system/assistant bubbles as provenance — never on owner/user messages", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T307", kind: "visible", surface: "composer", name: "Composer caret chords split cleanly: Home/End = field (message) start/end; Cmd/Ctrl+Left/Right = current line start/end (native)", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T308", kind: "exception", surface: "impl", name: "Main and sidebar transcripts use one message-bubble widget (build path) with different inputs — no second bubble constructor", reason: "same buildMsg constructor identity — vanilla function" },
  { id: "T309", kind: "visible", surface: "aside", name: "One agent conversation surface end-to-end: same UI widget (bubbles + composer) and same agent talk APIs for overseer, POs, and workers", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T309.1", kind: "visible", surface: "chrome", name: "Main and RHS mount one conversation widget (bubbles + composer + send) parameterised by agent id and density — compact composer is a styling option, not a second implementation", journeys: ["ticker"], families: ["frontier", "aside-sidebar"] },
  { id: "T309.2", kind: "exception", surface: "impl", name: "One agent-addressed conversation API family serves transcript, live stream, and send for every agent — overseer included, no privileged overseer-only chat wire for conversation", reason: "unified conversation API family — server wire" },
  { id: "T311", kind: "visible", surface: "fleet", name: "Fleet tree model badge shows the RUNNING model — observed truth seeded at launch/attach, never null on a live agent, cleared on kill", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T312", kind: "visible", surface: "fleet", name: "Fleet model badge condenses Fable (claude-fable-5) to F5 like Opus O5 / Sonnet S…", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T314", kind: "visible", surface: "transcript", name: "Message context tab is optional speaker then optional context — never repo-as-speaker or inventing PO as speaker", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T317", kind: "visible", surface: "other", name: "Convergence impatience escalates noise when open-mission idle exceeds reasonable bounds — overseer event then human-visible alert; noise is not satisfaction", journeys: ["ticker"] },
  { id: "T319", kind: "visible", surface: "other", name: "Human impatience alerts auto-clear on true satisfaction; every closed impatience incident yields a root mini-postmortem to the owner", journeys: ["ticker"] },
  { id: "T322", kind: "exception", surface: "doctrine", name: "make test-ui passes hermetically — the mocked WS drives the same connected handshake the product requires", reason: "make test-ui mocked-WS handshake — how we write UI tests" },
  { id: "T323", kind: "visible", surface: "fleet", name: "Fleet model badge matches current provider after migrate and never mixes stale model with a new company mark", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T324", kind: "exception", surface: "impl", name: "Fleet model badge binding is session truth rewritten on launch/migrate/rehydrate, with cache only between those events", reason: "badge binding cache on launch/migrate — server, paint is T311" },
  { id: "T325.1", kind: "exception", surface: "other", name: "Product owners run proactive-until-empty-then-sleep: keep kicking Build while the product frontier has ready leaves; sleep/idle without open-mission thrash when empty; stay interruptible for owner/overseer", reason: "PO proactive-until-empty-then-sleep — fleet policy, not paint" },
  { id: "T325.3", kind: "visible", surface: "aside", name: "Ideas are captured to bullseye or aside without evaporating in scrollback — durable intake + triage ceremony", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T326", kind: "visible", surface: "chrome", name: "System prompts and agent-facing surfaces consistently prefix bullseye ids as 🎯Tn; chat UI renders them as hover hotspots with the same frontier-card chrome (shared renderer)", journeys: ["ticker"], families: ["frontier", "aside-sidebar"] },
  { id: "T327", kind: "visible", surface: "transcript", name: "Main transcript progress chrome clears when a turn is routed into any aside — not only target asides", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T329", kind: "visible", surface: "aside", name: "RHS agent transcript shows one assistant bubble per owner turn — not one bubble per tool-round fragment", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T331", kind: "visible", surface: "frontier", name: "Frontier table: hierarchical target ids fit without ellipsis; id↔name and status↔fanout gaps are tight (no wasted chrome space)", journeys: ["frontier"], families: ["frontier"] },
  { id: "T332", kind: "visible", surface: "frontier", name: "Frontier table column gutters are roughly even — hierarchical ids fit without a 50px id↔name chasm or vanished status↔fanout gap", journeys: ["frontier"], families: ["frontier"] },
  { id: "T336", kind: "visible", surface: "transcript", name: "Page Up / scroll-up in main chat paints the next screenful without a half-second pregnant pause", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T337", kind: "exception", surface: "other", name: "Frontier auto-consume does not engage multi-device mobile megawork or leaves blocked by set_aside deps without explicit owner open", reason: "frontier auto-consume skip classes — policy, not table" },
  { id: "T338", kind: "exception", surface: "other", name: "Frontier auto-consume only engages true work leaves — not converging parents with active children or CGO/infrastructure megawork without owner open", reason: "frontier auto-consume true-work-leaves only — policy" },
  { id: "T339", kind: "exception", surface: "other", name: "Frontier auto-consume parks deferred/not-urgent leaves (voice/device later class) without owner open", reason: "frontier auto-consume parks deferred leaves — policy" },
  { id: "T340", kind: "visible", surface: "frontier", name: "Frontier table shows full hierarchical ids and even inter-column text gutters (T332 residual failure)", journeys: ["frontier"], families: ["frontier"] },
  { id: "T341", kind: "visible", surface: "transcript", name: "Main chat text does not continuously jiggle by ~1px from background reflow/pin thrash", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T342", kind: "exception", surface: "other", name: "Frontier consume deferred-classifier covers voice/iPad/VoicelabKit device DSP class (T28 residual after T339)", reason: "deferred-classifier voice/device DSP — policy" },
  { id: "T343", kind: "exception", surface: "other", name: "Frontier consume deferred-classifier parks T29-class generative-UI / DEFERRED future-work ambition", reason: "deferred-classifier T29-class — policy" },
  { id: "T345", kind: "visible", surface: "other", name: "Provider-feed automation liveness does not false-stall on cold start before first feed event", journeys: ["ticker"] },
  { id: "T346", kind: "exception", surface: "other", name: "Sentinel frontier_stall uses unattended-ready leaf count not raw graph frontier depth", reason: "sentinel frontier_stall classifier — not the table" },
  { id: "T347", kind: "visible", surface: "transcript", name: "Transcript reload paints end-first without scroll parade and only materializes viewport plus a few screens above", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T348", kind: "visible", surface: "fleet", name: "Claude fleet badges always show condensed version subscript when model is known — not bare company mark", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T349", kind: "visible", surface: "composer", name: "Main chat composer stays responsive — no multi-second input freezes or Firefox slow-script dialogs during normal use", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T350", kind: "visible", surface: "transcript", name: "Main chat text does not randomly jiggle ~1px — T341 regression restored under live pin/virtualize thrash", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T351", kind: "visible", surface: "transcript", name: "Main chat has zero residual vertical jiggle in daily use after T350 — product path not hermetic-only", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T353", kind: "exception", surface: "other", name: "RSI coach retrospectively mines history (transcripts, git, eventlog) — not only forward drip of new appends", reason: "RSI coach retrospective mine — ops, not cockpit chrome" },
  { id: "T354", kind: "visible", surface: "other", name: "Owner can see RSI coach judgments and their dispositions in the daily UI — bare list is enough for v1", journeys: ["ticker"] },
  { id: "T355", kind: "visible", surface: "other", name: "Owner interaction converges: level-triggered healthy chat with recovery generalized from post-restart dual-path", journeys: ["ticker"] },
  { id: "T361", kind: "visible", surface: "transcript", name: "A degraded owner interaction is visible and self-healing in the client, not only on the server", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T362", kind: "visible", surface: "transcript", name: "ux_state frames never appear as owner chat bubbles", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T363", kind: "visible", surface: "transcript", name: "Transcript scroll-up preserves viewport when older content prepends (no jump/stutter)", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T365", kind: "visible", surface: "aside", name: "Target asides show 🎯 chrome (not 💡 light bulb)", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T366", kind: "visible", surface: "composer", name: "Tab cycles focus between main and sidebar composers when sidebar visible", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T549", kind: "visible", surface: "composer", name: "Tab never walks cockpit chrome — only the two message boxes", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T367", kind: "visible", surface: "aside", name: "Sidebar messages persist across reload and daemon reboot like main chat", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T368", kind: "visible", surface: "composer", name: "Composer prefix commands still open when message starts with image markers", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T369", kind: "visible", surface: "transcript", name: "Structured design-choice UX in chat (not raw markdown tables)", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T371", kind: "visible", surface: "aside", name: "Aside and main composers share one send/display path (no vanish)", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T372", kind: "visible", surface: "aside", name: "One chat widget + one agent contract: main and every agent are indistinguishable except role", journeys: ["aside"], families: ["aside-sidebar"] },
  { id: "T374", kind: "visible", surface: "transcript", name: "No unhandled window.onerror in owner cockpit", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T375", kind: "exception", surface: "other", name: "Owner cockpit is never served a mid-edit working tree while fleet workers are editing web/", reason: "serve mid-edit working tree — daemon serve path, not React" },
  { id: "T380", kind: "exception", surface: "other", name: "A product owner cannot sit idle on a non-empty frontier without the overseer being told why", reason: "PO idle-on-frontier overseer alarm — policy" },
  { id: "T381", kind: "visible", surface: "transcript", name: "Agent reports render as markdown — only what the owner actually typed is painted verbatim", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T382", kind: "visible", surface: "transcript", name: "An owner turn is painted exactly once under every provider, and the internal user-turn marker never reaches the transcript", journeys: ["send", "connect"], families: ["fold", "transcript-geom"] },
  { id: "T383", kind: "visible", surface: "fleet", name: "Fleet tree selection is sticky — a background refresh never moves the owner's selection", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T384", kind: "visible", surface: "transcript", name: "Owner turns persist in the same shape as agent turns, and rehydration never re-appends history", journeys: ["send", "connect"], families: ["fold", "transcript-geom"] },
  { id: "T390", kind: "visible", surface: "ticker", name: "The owner can see plan usage in the cockpit — percent remaining and next rollover, per backend", journeys: ["ticker"], families: ["plan-ticker"] },
  { id: "T390.1.3", kind: "visible", surface: "ticker", name: "Exhausted Claude plan-usage still paints the boxed pair, not a collapsed icon", journeys: ["ticker"], families: ["plan-ticker"] },
  { id: "T390.1.4", kind: "exception", surface: "other", name: "Overseer can read the header plan-usage snapshot via jevons_plan_usage", reason: "jevons_plan_usage MCP read, not ticker paint" },
  { id: "T390.1.5", kind: "exception", surface: "other", name: "Daemon plan-usage policy steers mint and migrates off exhausted providers — independent of ticker paint", reason: "mint/migrate eligibility policy, independent of ticker paint" },
  { id: "T390.1.5.1", kind: "exception", surface: "other", name: "Session remaining-low or exhausted is a server eligibility veto", reason: "mint/migrate eligibility policy, independent of ticker paint" },
  { id: "T390.1.6", kind: "visible", surface: "ticker", name: "Plan-usage transition points are a server-owned static feed; ticker and switch policy both consume them", journeys: ["ticker"], families: ["plan-ticker"] },
  { id: "T390.1.6.1", kind: "visible", surface: "ticker", name: "Early-window burn is damped so week-start overspend is not hot", journeys: ["ticker"], families: ["plan-ticker"] },
  { id: "T407", kind: "exception", surface: "other", name: "The frontier-stall sentinel distinguishes a blocked fleet from an unattended one, and never prescribes spawning into a wall", reason: "frontier-stall sentinel blocked vs unattended — classifier" },
  { id: "T412", kind: "visible", surface: "fleet", name: "A registry status of running means a live conversation exists — an agent whose session was never materialized is reported as dead, not nudged forever", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T416", kind: "exception", surface: "delivery", name: "A large message to a fleet agent is submitted, not left sitting in the composer, and jevons_agent_send never reports sent for a paste that never became a turn", reason: "jevons_agent_send turn-begin honesty — MCP, not cockpit" },
  { id: "T426", kind: "exception", surface: "delivery", name: "A context compaction does not make an agent invisible to the daemon: the successor's event stream is wired, so its turn ends are observed, its send queue drains, and its reports still reach the overseer", reason: "compaction successor visibility — daemon, not cockpit" },
  { id: "T433", kind: "exception", surface: "other", name: "A frontier leaf whose spawn brief never reaches the worker is surfaced to its product owner, not silently parked", reason: "spawn-brief never reached worker — fleet policy" },
  { id: "T447", kind: "exception", surface: "delivery", name: "A message waiting in a receiver's composer queue is readable as waiting — the delivery instrument names queued_command as the positive in-flight signal, so an accepted message is never diagnosed as lost", reason: "queued_command delivery instrument — MCP, not cockpit" },
  { id: "T449", kind: "exception", surface: "other", name: "A target whose code has landed and whose only residue is an owner taste gate is not an unconsumed frontier leaf — the ledger distinguishes awaiting-owner-verification from untouched, and frontier-consume does not spawn against it", reason: "owner taste-gate residue — process, not cockpit paint" },
  { id: "T474", kind: "visible", surface: "fleet", name: "A bare-thread Launch never re-mints a work agent as a purposeless aside", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T478", kind: "visible", surface: "composer", name: "After send, the empty composer stays one control tall — not the wrapped placeholder", journeys: ["composer"], families: ["composer-keys", "composer-chrome"] },
  { id: "T479", kind: "visible", surface: "transcript", name: "A Grok token-stream for one inline-code path paints as one bubble, not one bubble per token", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T480", kind: "visible", surface: "fold", name: "Every bubble collapses by size alone — same T106 clip on main and Transcript", journeys: ["fold-md"], families: ["clip", "markdown", "fold"] },
  { id: "T481", kind: "exception", surface: "impl", name: "Every provider event that reaches the daemon is persisted in that agent's journal; display may ignore, the tape may not", reason: "journal must persist every event — tape, not pixels" },
  { id: "T482", kind: "exception", surface: "impl", name: "A snapped transcript row does not ResizeObserver-loop the cockpit into a hang", reason: "ResizeObserver snap-lock loop — vanilla row measure" },
  { id: "T483", kind: "visible", surface: "transcript", name: "Auto history hydrate stops after the connect tail — further pages only when the owner is at the top", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T484", kind: "exception", surface: "impl", name: "A settled cockpit does not restyle and rematerialize every frame", reason: "noteRowHeightChange rematerialize — vanilla reconciler" },
  { id: "T485", kind: "exception", surface: "impl", name: "Frontier hover cards are built on first hover and reused until the row source changes", reason: "lazy InstantTip skip-unchanged remount — vanilla attach" },
  { id: "T486", kind: "exception", surface: "impl", name: "A snap lock taller than the natural box shrinks on the next measure", reason: "snap-lock minHeight shrink — geometry internals" },
  { id: "T489", kind: "visible", surface: "other", name: "Phase 2 — a normal workday in the cockpit is not a fight with the chrome", journeys: ["ticker"] },
  { id: "T491", kind: "visible", surface: "transcript", name: "Connect replay of the last N owner turns paints one virtual-list row per turn — not one leftover bubble with every message stacked at top 0", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T493", kind: "exception", surface: "doctrine", name: "Cockpit on-screen evidence is checkVisibility + centre hit-test + Vision OCR — not a model caption", reason: "checkVisibility + hit-test + OCR evidence method" },
  { id: "T494", kind: "visible", surface: "transcript", name: "Daily cockpit connect shows the replay tail in the #messages viewport — not an empty pane over a tall canvas", journeys: ["connect"], families: ["fold", "transcript-geom"] },
  { id: "T494.1.2", kind: "exception", surface: "impl", name: "Transcript layout is a function of the transcript and width, not of scroll history", reason: "prefix-sum layout is f(transcript, width) — virtual-list math" },
  { id: "T496", kind: "visible", surface: "transcript", name: "Overseer final replies always paint as owner-visible main-chat bubbles", journeys: ["send", "connect"], families: ["fold", "transcript-geom"] },
  { id: "T499", kind: "exception", surface: "other", name: "Ready frontier leaves prefer recent targets over long-lived ones by default", reason: "ready-leaf recency preference — consume policy" },
  { id: "T504", kind: "visible", surface: "transcript", name: "Owner chat renders replies after the message that provoked them — a user bubble is a stream barrier", journeys: ["send", "connect"], families: ["fold", "transcript-geom"] },
  { id: "T506", kind: "visible", surface: "fleet", name: "Fleet-tree model selector is comfortably readable and tappable at normal desktop zoom", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T507", kind: "visible", surface: "fleet", name: "OpenAI/Codex fleet company mark is the ChatGPT logo geometry, not the local stand-in", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T508", kind: "visible", surface: "fleet", name: "Bedrock fleet model selectors show the Amazon Bedrock mark before the vendor mark", journeys: ["fleet"], families: ["fleet-tree"] },
  { id: "T513", kind: "visible", surface: "transcript", name: "Briefs addressed to a fleet agent never land in the overseer chat as if they were that agent", journeys: ["send", "connect"], families: ["fold", "transcript-geom"] },
  { id: "T517", kind: "exception", surface: "other", name: "Plan-usage force-migrate does not bounce the product owner onto a new provider", reason: "PO force-migrate veto — routing, not ticker paint" },
  { id: "T522", kind: "exception", surface: "doctrine", name: "TestSidebarJournalDedupesProviderEcho passes on a clean checkout of master", reason: "TestSidebarJournalDedupesProviderEcho hermetic — product is T281" },
];

export function censusVisible(): CensusRow[] {
  return CENSUS.filter((r) => r.kind === 'visible');
}

export function censusExceptions(): CensusRow[] {
  return CENSUS.filter((r) => r.kind === 'exception');
}

export function censusIds(): string[] {
  return CENSUS.map((r) => r.id);
}

