// Copyright 2026 Marcelo Cantos
// SPDX-License-Identifier: Apache-2.0

/** T540.3/T540.5 close map: every visible census id has a pocket + kind.
 *
 * Vanilla :13706 pockets (referent for paint):
 *   composer, transcript, fold, fleet, aside, frontier (table+card+graph),
 *   ticker, chrome (layout/pixel). InstantTip hit-region is frontier/ticker.
 * Referent for data is the live API payload. kind=mapper is T540.6 composition.
 */

export type ClosePocket = 'composer' | 'transcript' | 'fold' | 'fleet' | 'aside' | 'frontier' | 'ticker' | 'chrome';
export type CloseKind = 'mapper' | 'hermetic' | 'journey' | 'skip';

export type CloseAssignment = {
  id: string;
  pocket: ClosePocket;
  kind: CloseKind;
  reason: string;
};

export const CLOSE: readonly CloseAssignment[] = [
  { id: 'T21', pocket: 'composer', kind: 'skip', reason: 'mention-only covers-list — classified to composer pocket; J24 live fail does not name this id yet' },
  { id: 'T23', pocket: 'transcript', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T30.2', pocket: 'transcript', kind: 'skip', reason: 'journey is the arbiter (J19)' },
  { id: 'T39', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T52', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J22 live fail does not name this id yet' },
  { id: 'T55', pocket: 'fold', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T57', pocket: 'fold', kind: 'skip', reason: 'mention-only covers-list — classified to fold pocket; J23 live fail does not name this id yet' },
  { id: 'T58', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T59', pocket: 'fold', kind: 'journey', reason: 'journey is the arbiter (J23 live fail)' },
  { id: 'T63', pocket: 'transcript', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T64', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T65', pocket: 'aside', kind: 'skip', reason: 'journey is the arbiter (J26)' },
  { id: 'T66', pocket: 'fold', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T68', pocket: 'fleet', kind: 'journey', reason: 'journey is the arbiter (J25 live fail)' },
  { id: 'T69', pocket: 'composer', kind: 'skip', reason: 'mention-only covers-list — classified to composer pocket; J24 live fail does not name this id yet' },
  { id: 'T70', pocket: 'composer', kind: 'skip', reason: 'named residual: pixel-identical chrome' },
  { id: 'T70.1', pocket: 'composer', kind: 'skip', reason: 'named residual: pixel-identical chrome' },
  { id: 'T71', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T72', pocket: 'fleet', kind: 'skip', reason: 'mention-only covers-list — classified to fleet pocket; J25 live fail does not name this id yet' },
  { id: 'T72.1', pocket: 'fleet', kind: 'journey', reason: 'journey is the arbiter (J25 live fail)' },
  { id: 'T73', pocket: 'fleet', kind: 'skip', reason: 'mention-only covers-list — classified to fleet pocket; J25 live fail does not name this id yet' },
  { id: 'T74', pocket: 'fold', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T75', pocket: 'fold', kind: 'skip', reason: 'mention-only covers-list — classified to fold pocket; J23 live fail does not name this id yet' },
  { id: 'T76', pocket: 'composer', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T77', pocket: 'fold', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T80', pocket: 'composer', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T81', pocket: 'fleet', kind: 'skip', reason: 'mention-only covers-list — classified to fleet pocket; J25 live fail does not name this id yet' },
  { id: 'T82', pocket: 'fleet', kind: 'skip', reason: 'mention-only covers-list — classified to fleet pocket; J25 live fail does not name this id yet' },
  { id: 'T83', pocket: 'ticker', kind: 'skip', reason: 'mention-only covers-list — classified to ticker pocket; J28 live fail does not name this id yet' },
  { id: 'T83.1', pocket: 'ticker', kind: 'skip', reason: 'not ported: copy Mermaid source/image' },
  { id: 'T84', pocket: 'fleet', kind: 'skip', reason: 'mention-only covers-list — classified to fleet pocket; J25 live fail does not name this id yet' },
  { id: 'T87', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T88', pocket: 'composer', kind: 'skip', reason: 'mention-only covers-list — classified to composer pocket; J24 live fail does not name this id yet' },
  { id: 'T89', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T91', pocket: 'transcript', kind: 'skip', reason: 'not ported: relTime is always-visible, not InstantTip' },
  { id: 'T93', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T94', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T95', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T95.1', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T99', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T103', pocket: 'ticker', kind: 'skip', reason: 'mention-only covers-list — classified to ticker pocket; J28 live fail does not name this id yet' },
  { id: 'T106', pocket: 'fold', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T111.3', pocket: 'fleet', kind: 'skip', reason: 'mention-only covers-list — classified to fleet pocket; J25 live fail does not name this id yet' },
  { id: 'T113', pocket: 'composer', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T115', pocket: 'fleet', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T116', pocket: 'transcript', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T117', pocket: 'ticker', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T118', pocket: 'fleet', kind: 'skip', reason: 'mention-only covers-list — classified to fleet pocket; J25 live fail does not name this id yet' },
  { id: 'T119', pocket: 'transcript', kind: 'skip', reason: 'journey is the arbiter (J19)' },
  { id: 'T119.1', pocket: 'transcript', kind: 'skip', reason: 'journey is the arbiter (J19)' },
  { id: 'T119.6', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T119.7', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T119.8', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T122', pocket: 'transcript', kind: 'skip', reason: 'not ported: InstantTip-class hover' },
  { id: 'T123', pocket: 'composer', kind: 'journey', reason: 'journey is the arbiter (J24 live fail)' },
  { id: 'T124', pocket: 'fleet', kind: 'skip', reason: 'journey is the arbiter (J25/J26)' },
  { id: 'T126', pocket: 'composer', kind: 'journey', reason: 'journey is the arbiter (J24 live fail)' },
  { id: 'T127', pocket: 'composer', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T131', pocket: 'frontier', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T132', pocket: 'composer', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T133', pocket: 'composer', kind: 'skip', reason: 'mention-only covers-list — classified to composer pocket; J24 live fail does not name this id yet' },
  { id: 'T134', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T135', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T136', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T138', pocket: 'ticker', kind: 'skip', reason: 'mention-only covers-list — classified to ticker pocket; J19 live fail does not name this id yet' },
  { id: 'T140', pocket: 'ticker', kind: 'skip', reason: 'mention-only covers-list — classified to ticker pocket; J28 live fail does not name this id yet' },
  { id: 'T143', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T145', pocket: 'fold', kind: 'skip', reason: 'mention-only covers-list — classified to fold pocket; J23 live fail does not name this id yet' },
  { id: 'T146', pocket: 'fold', kind: 'skip', reason: 'mention-only covers-list — classified to fold pocket; J23 live fail does not name this id yet' },
  { id: 'T147', pocket: 'fold', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T149', pocket: 'composer', kind: 'skip', reason: 'mention-only covers-list — classified to composer pocket; J24 live fail does not name this id yet' },
  { id: 'T150', pocket: 'fold', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T151', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T152', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T153', pocket: 'composer', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T154', pocket: 'composer', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T157', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T159', pocket: 'transcript', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T161', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T164', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T166', pocket: 'fold', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T167', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T168', pocket: 'frontier', kind: 'mapper', reason: 'product mapper toFrontierRows + painted card sections' },
  { id: 'T173', pocket: 'frontier', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T174', pocket: 'frontier', kind: 'skip', reason: 'named residual: pixel-identical chrome (with T340)' },
  { id: 'T175', pocket: 'frontier', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T177', pocket: 'frontier', kind: 'skip', reason: 'named residual: pixel-identical chrome (with T340)' },
  { id: 'T179', pocket: 'frontier', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T181', pocket: 'frontier', kind: 'mapper', reason: 'product mapper toFrontierRows + painted card sections' },
  { id: 'T182', pocket: 'frontier', kind: 'skip', reason: 'not ported: ft-play-btn is dead chrome' },
  { id: 'T183', pocket: 'composer', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T184', pocket: 'frontier', kind: 'mapper', reason: 'product mapper toFrontierRows + painted card sections' },
  { id: 'T185', pocket: 'frontier', kind: 'journey', reason: 'journey is the arbiter (J27 live fail)' },
  { id: 'T186', pocket: 'frontier', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T187', pocket: 'frontier', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T189', pocket: 'frontier', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T190', pocket: 'frontier', kind: 'skip', reason: 'mention-only covers-list — classified to frontier pocket; J27 live fail does not name this id yet' },
  { id: 'T192', pocket: 'composer', kind: 'skip', reason: 'mention-only covers-list — classified to composer pocket; J24 live fail does not name this id yet' },
  { id: 'T196', pocket: 'frontier', kind: 'skip', reason: 'mention-only covers-list — classified to frontier pocket; J27 live fail does not name this id yet' },
  { id: 'T198', pocket: 'frontier', kind: 'skip', reason: 'not ported: no engagement rows' },
  { id: 'T199', pocket: 'frontier', kind: 'skip', reason: 'mention-only covers-list — classified to frontier pocket; J27 live fail does not name this id yet' },
  { id: 'T200', pocket: 'fleet', kind: 'skip', reason: 'mention-only covers-list — classified to fleet pocket; J25 live fail does not name this id yet' },
  { id: 'T202', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T203', pocket: 'frontier', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T204', pocket: 'ticker', kind: 'skip', reason: 'mention-only covers-list — classified to ticker pocket; J28 live fail does not name this id yet' },
  { id: 'T205', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T208', pocket: 'frontier', kind: 'skip', reason: 'journey is the arbiter (J27 tab-stick)' },
  { id: 'T210', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J22 live fail does not name this id yet' },
  { id: 'T211', pocket: 'fleet', kind: 'skip', reason: 'mention-only covers-list — classified to fleet pocket; J25 live fail does not name this id yet' },
  { id: 'T216', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T217', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T221', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T223', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J22 live fail does not name this id yet' },
  { id: 'T224', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T227', pocket: 'composer', kind: 'skip', reason: 'mention-only covers-list — classified to composer pocket; J24 live fail does not name this id yet' },
  { id: 'T228', pocket: 'composer', kind: 'skip', reason: 'mention-only covers-list — classified to composer pocket; J22 live fail does not name this id yet' },
  { id: 'T230', pocket: 'frontier', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T231', pocket: 'frontier', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T233', pocket: 'transcript', kind: 'skip', reason: 'not ported: InstantTip-class hover' },
  { id: 'T235', pocket: 'composer', kind: 'skip', reason: 'journey is the arbiter (composer queue residual)' },
  { id: 'T237', pocket: 'ticker', kind: 'skip', reason: 'mention-only covers-list — classified to ticker pocket; J28 live fail does not name this id yet' },
  { id: 'T238', pocket: 'transcript', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T239', pocket: 'composer', kind: 'skip', reason: 'mention-only covers-list — classified to composer pocket; J24 live fail does not name this id yet' },
  { id: 'T240', pocket: 'transcript', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T241', pocket: 'composer', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T242', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T245', pocket: 'transcript', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T246', pocket: 'fold', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T247', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T248', pocket: 'ticker', kind: 'journey', reason: 'journey is the arbiter (J28 live fail)' },
  { id: 'T249', pocket: 'transcript', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T250', pocket: 'aside', kind: 'journey', reason: 'journey is the arbiter (J26 live fail)' },
  { id: 'T251', pocket: 'aside', kind: 'journey', reason: 'journey is the arbiter (J26 live fail)' },
  { id: 'T252', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T255', pocket: 'frontier', kind: 'skip', reason: 'not ported: depends on T182' },
  { id: 'T256', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T257', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T258', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T259', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T260', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T261', pocket: 'fold', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T263', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T264', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T265', pocket: 'aside', kind: 'skip', reason: 'journey is the arbiter (J26)' },
  { id: 'T266', pocket: 'frontier', kind: 'skip', reason: 'not ported: target-ask chrome' },
  { id: 'T267', pocket: 'frontier', kind: 'skip', reason: 'not ported: target-ask chrome' },
  { id: 'T268', pocket: 'frontier', kind: 'skip', reason: 'mention-only covers-list — classified to frontier pocket; J27 live fail does not name this id yet' },
  { id: 'T269', pocket: 'aside', kind: 'skip', reason: 'not ported: InstantTip-class hover dismiss' },
  { id: 'T270', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T271', pocket: 'frontier', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T272', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T273', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T274', pocket: 'frontier', kind: 'skip', reason: 'mention-only covers-list — classified to frontier pocket; J27 live fail does not name this id yet' },
  { id: 'T275', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T278', pocket: 'frontier', kind: 'skip', reason: 'not ported: depends on T182' },
  { id: 'T279', pocket: 'transcript', kind: 'journey', reason: 'journey is the arbiter (J22 live fail)' },
  { id: 'T280', pocket: 'frontier', kind: 'skip', reason: 'named residual: pixel-identical chrome' },
  { id: 'T281', pocket: 'transcript', kind: 'journey', reason: 'journey is the arbiter (J22 live fail)' },
  { id: 'T285.2', pocket: 'fleet', kind: 'skip', reason: 'named residual: pixel-identical chrome' },
  { id: 'T287', pocket: 'fleet', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T289', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T293', pocket: 'fleet', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T294', pocket: 'frontier', kind: 'skip', reason: 'named residual: pixel-identical chrome' },
  { id: 'T295', pocket: 'fleet', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T296', pocket: 'fleet', kind: 'skip', reason: 'mention-only covers-list — classified to fleet pocket; J25 live fail does not name this id yet' },
  { id: 'T298', pocket: 'fleet', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T299', pocket: 'fleet', kind: 'skip', reason: 'named residual: pixel-identical chrome' },
  { id: 'T300', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T301', pocket: 'fleet', kind: 'skip', reason: 'mention-only covers-list — classified to fleet pocket; J25 live fail does not name this id yet' },
  { id: 'T302', pocket: 'fleet', kind: 'skip', reason: 'mention-only covers-list — classified to fleet pocket; J25 live fail does not name this id yet' },
  { id: 'T306', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T307', pocket: 'composer', kind: 'skip', reason: 'journey is the arbiter (J24 Home/End)' },
  { id: 'T309', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T309.1', pocket: 'ticker', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T311', pocket: 'fleet', kind: 'skip', reason: 'mention-only covers-list — classified to fleet pocket; J25 live fail does not name this id yet' },
  { id: 'T312', pocket: 'fleet', kind: 'skip', reason: 'mention-only covers-list — classified to fleet pocket; J25 live fail does not name this id yet' },
  { id: 'T314', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T317', pocket: 'ticker', kind: 'skip', reason: 'mention-only covers-list — classified to ticker pocket; J28 live fail does not name this id yet' },
  { id: 'T319', pocket: 'ticker', kind: 'skip', reason: 'mention-only covers-list — classified to ticker pocket; J28 live fail does not name this id yet' },
  { id: 'T323', pocket: 'fleet', kind: 'skip', reason: 'mention-only covers-list — classified to fleet pocket; J25 live fail does not name this id yet' },
  { id: 'T325.3', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T326', pocket: 'frontier', kind: 'mapper', reason: 'product mapper toFrontierRows + painted card sections' },
  { id: 'T327', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T329', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T331', pocket: 'frontier', kind: 'skip', reason: 'named residual: pixel-identical chrome (with T340)' },
  { id: 'T332', pocket: 'frontier', kind: 'skip', reason: 'named residual: pixel-identical chrome (with T340)' },
  { id: 'T336', pocket: 'transcript', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T340', pocket: 'frontier', kind: 'skip', reason: 'named residual: pixel-identical chrome' },
  { id: 'T341', pocket: 'transcript', kind: 'skip', reason: 'named residual: pixel-identical chrome' },
  { id: 'T345', pocket: 'ticker', kind: 'skip', reason: 'mention-only covers-list — classified to ticker pocket; J28 live fail does not name this id yet' },
  { id: 'T347', pocket: 'transcript', kind: 'skip', reason: 'journey is the arbiter (J19)' },
  { id: 'T348', pocket: 'fleet', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T349', pocket: 'composer', kind: 'skip', reason: 'mention-only covers-list — classified to composer pocket; J24 live fail does not name this id yet' },
  { id: 'T350', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T351', pocket: 'transcript', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T354', pocket: 'ticker', kind: 'skip', reason: 'mention-only covers-list — classified to ticker pocket; J28 live fail does not name this id yet' },
  { id: 'T355', pocket: 'ticker', kind: 'skip', reason: 'mention-only covers-list — classified to ticker pocket; J28 live fail does not name this id yet' },
  { id: 'T361', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T362', pocket: 'transcript', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T363', pocket: 'transcript', kind: 'skip', reason: 'journey is the arbiter (J19)' },
  { id: 'T365', pocket: 'aside', kind: 'skip', reason: 'mention-only covers-list — classified to aside pocket; J26 live fail does not name this id yet' },
  { id: 'T366', pocket: 'composer', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T367', pocket: 'aside', kind: 'skip', reason: 'journey is the arbiter (J26 persist residual)' },
  { id: 'T368', pocket: 'composer', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T369', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T371', pocket: 'aside', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T372', pocket: 'aside', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T374', pocket: 'ticker', kind: 'skip', reason: 'mention-only covers-list — classified to ticker pocket; J19 live fail does not name this id yet' },
  { id: 'T381', pocket: 'transcript', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T382', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J22 live fail does not name this id yet' },
  { id: 'T383', pocket: 'fleet', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T384', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J22 live fail does not name this id yet' },
  { id: 'T390', pocket: 'ticker', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T390.1.3', pocket: 'ticker', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T390.1.6', pocket: 'ticker', kind: 'skip', reason: 'served /api/plan-usage/thresholds — daily path' },
  { id: 'T390.1.6.1', pocket: 'ticker', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T412', pocket: 'fleet', kind: 'skip', reason: 'mention-only covers-list — classified to fleet pocket; J25 live fail does not name this id yet' },
  { id: 'T474', pocket: 'fleet', kind: 'skip', reason: 'mention-only covers-list — classified to fleet pocket; J25 live fail does not name this id yet' },
  { id: 'T478', pocket: 'composer', kind: 'skip', reason: 'mention-only covers-list — classified to composer pocket; J24 live fail does not name this id yet' },
  { id: 'T479', pocket: 'transcript', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T480', pocket: 'fold', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T483', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T489', pocket: 'ticker', kind: 'skip', reason: 'mention-only covers-list — classified to ticker pocket; J28 live fail does not name this id yet' },
  { id: 'T491', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T494', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J19 live fail does not name this id yet' },
  { id: 'T496', pocket: 'transcript', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T504', pocket: 'transcript', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T506', pocket: 'fleet', kind: 'skip', reason: 'named residual: pixel-identical chrome' },
  { id: 'T507', pocket: 'fleet', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T508', pocket: 'fleet', kind: 'hermetic', reason: 'passing hermetic itOracle in family file' },
  { id: 'T513', pocket: 'transcript', kind: 'skip', reason: 'mention-only covers-list — classified to transcript pocket; J22 live fail does not name this id yet' },
];

export const CONTENT_MAPPER_IDS: readonly string[] = CLOSE.filter((r) => r.kind === "mapper").map((r) => r.id);

export function closeById(): Map<string, CloseAssignment> {
  return new Map(CLOSE.map((r) => [r.id, r]));
}

